language: java
branches:
  only:
    - master
    - "/^feature-.*/"
    - "/^hotfix-.*/"
    - "/^test-.*/"
    - "/^fix-.*/"
    - "/^chore-.*/"
    - "/^doc-.*/"
    - "/^v.*$/"

jobs:
  include:
    - stage: print_settigns.xml
      name: cat settings.xml
      script: ls /
    - stage: compile
      name: openjdk 11 / Build / Test
      jdk: openjdk11
      script: mvn clean test install --settings settings.xml
    - stage: package --settings settings.xml & publish --settings settings.xml
      name: package docker image and push to registry
      jdk: openjdk11
      script: make build-docker-native-image && make push-docker-image
notifications:
  email:
    recipients:
      - pablo.gonzalez.granados@gmail.com
    on_success: always
    on_failure: always
before_install:
  - openssl aes-256-cbc -K $encrypted_35cc27c77d20_key -iv $encrypted_35cc27c77d20_iv
    -in settings.xml.enc -out settings.xml -d
