environments:
  default:
    values:
      - Namespace: test-pablo

releases:
  - name: code-with-quarkus
    namespace: {{ .Values.Namespace }}
    chart: code-with-quarkus
    version: 0.0.7
    values:
      - ./code-with-quarkus/values.yaml
