apiVersion: apps/v1
kind: HorizontalPodAutoscaler
metadata:
  name: code-with-quarkus-app
  namespace: test-pablo
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: code-with-quarkus-app
  minReplicas: 10
  maxReplicas: 50
  targetCPUUtilizationPercentage: 60