apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deputyv2
  namespace: tongariv2-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: deputyv2
  minReplicas: 10
  maxReplicas: 50
  targetCPUUtilizationPercentage: 60