apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deputyv2
  namespace: tongariv2-prod
spec:
  revisionHistoryLimit: 5
  replicas: 10
  selector:
    matchLabels:
      app: deputyv2
  template:
    metadata:
      labels:
        app: deputyv2
    spec:
      containers:
      - image: eu.gcr.io/store_dev_001/tongariv2:v2.0.89
        livenessProbe:
          httpGet:
             path: deputy/v2/health/
             port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
             path: deputy/v2/health/
             port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 80m
            memory: 65Mi
          limits:
            cpu: 200m
            memory: 250Mi
        imagePullPolicy: Always
        name: deputyv2
        command:
        - /app
        - deputy
        env:
        - name: CONFIG_PATH
          value: /config
        - name: ENVIROMENT
          value: STA
        - name: VERSION
          value: "2.0.0-SNAPSHOT"
        ports:
        - name: www
          containerPort: 8080
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - name: config
        secret:
          secretName: config
