apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-with-quarkus-app
  namespace: test-pablo
spec:
  revisionHistoryLimit: 5
  replicas: 10
  selector:
    matchLabels:
      app: code-with-quarkus-app
  template:
    metadata:
      labels:
        app: code-with-quarkus-app
    spec:
      containers:
      - image: pjgg/code-with-quarkus:09b09cc
        livenessProbe:
          httpGet:
             path: health/live
             port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
             path: health/ready
             port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 80m
            memory: 35Mi
          limits:
            cpu: 200m
            memory: 100Mi
        imagePullPolicy: Always
        name: code-with-quarkus-app
        ports:
        - name: www
          containerPort: 8080
